Dev/fix ubt race no async
JetBrains/UnrealLink pull request #127
Opened 2021-08-06 15:37 UTC by DecoyRS

2021-08-06 15:59 UTC, real-mikhail requested changes
Added one comment. Also is it me or lines from 385 to 388 contain some nonsense?

2021-08-06 15:59 UTC, real-mikhail commented on src/dotnet/RiderPlugin.UnrealLink/PluginInstaller/UnrealPluginInstaller.cs
> +                    Console.Out.WriteLine("Hello~!");
Hi! 😃

2021-08-06 16:03 UTC, DecoyRS commented on src/dotnet/RiderPlugin.UnrealLink/PluginInstaller/UnrealPluginInstaller.cs
> +                    Console.Out.WriteLine("Hello~!");
rofl

2021-08-06 16:05 UTC, DecoyRS commented
@real-mikhail jeez, I wonder how long this comment was hiding there. Good catch! I'll nuke it

2021-08-09 09:02 UTC, real-mikhail approved these changes

2021-08-09 10:35 UTC, merged